[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcbackend"
version = "0.5.4"
description = "Framework agnostic backends for MCMC sample storage"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.12"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [ { name = "Michael Osthege", email = "michael.osthege@outlook.com" } ]
urls = { "Homepage" = "https://github.com/michaelosthege/mcbackend" }
classifiers = [
  "Programming Language :: Python",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
]
dependencies = [
  "betterproto==2.0.0b7",
  "hagelkorn",
  "numpy",
  "pandas",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"mcbackend" = ["py.typed"]
[tool.pytest.ini_options]
xfail_strict=true

[tool.black]
line-length = 100

[tool.mypy]
exclude = [
  "^mcbackend/test_*",
]
ignore_missing_imports = true
